# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Ui\Http\:
        resource: '../src/Ui/Http/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    GuzzleHttp\Client: ~
    Psr\Http\Client\ClientInterface: '@GuzzleHttp\Client'

    App\Infrastructure\Geocoder\Gmaps\GmapsGeocoderClient:
        arguments:
            $apiKey: '%env(GOOGLE_GEOCODING_API_KEY)%'
            $client: '@Psr\Http\Client\ClientInterface'

    App\Infrastructure\Geocoder\Hmaps\HereMapsGeocoderClient:
        arguments:
            $apiKey: '%env(HEREMAPS_GEOCODING_API_KEY)%'
            $client: '@Psr\Http\Client\ClientInterface'

    App\Ui\Http\GmapsCoordinatesController:
        arguments:
            $geocoder: !service
                class: App\Application\Geocoder\Geocoder
                arguments:
                    $geocoders: ['@App\Infrastructure\Geocoder\Cache\DoctrineCacheGeocoderClient', '@App\Infrastructure\Geocoder\Gmaps\GmapsGeocoderClient']
                    $resolvedAddressRepository: '@App\Application\Repository\ResolvedAddressRepository'

    App\Ui\Http\HereMapsCoordinatesController:
        arguments:
            $geocoder: !service
                class: App\Application\Geocoder\Geocoder
                arguments:
                    $geocoders: ['@App\Infrastructure\Geocoder\Cache\DoctrineCacheGeocoderClient', '@App\Infrastructure\Geocoder\Hmaps\HereMapsGeocoderClient']
                    $resolvedAddressRepository: '@App\Application\Repository\ResolvedAddressRepository'

    App\Ui\Http\CoordinatesController:
        arguments:
            $geocoder: !service
                class: App\Application\Geocoder\Geocoder
                arguments:
                    $geocoders: ['@App\Infrastructure\Geocoder\Cache\DoctrineCacheGeocoderClient', '@App\Infrastructure\Geocoder\Dummy\DummyGeocoderClient']
                    $resolvedAddressRepository: '@App\Application\Repository\ResolvedAddressRepository'
